export const GetUsers = {
    GET_USERS_START: "GET_USERS_START",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    NEW_USERS_SUCCESS: "NEW_USERS_SUCCESS",
    DELETE_USERS: "DELETE_USERS"
}